contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 1.1.45
    packID: FeedAWS
    packName: AWS Feed
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook handles the tagging of AWS indicators. Specify the tag
  to apply to these indicators in the playbook inputs. An example tag will be approved_white.
  If no inputs are specified, the indicators will be tagged for manual review. The
  user can specify whether a manual review incident is required.
id: TIM - Process AWS indicators
inputs:
- description: 'Use this input to define which tag to apply to AWS indicators. An
    example tag can be whitelist_review. If no tags are specified in the input, the
    tag whitelist_review will be used. '
  key: AWSIndicatorTagName
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: sourceBrands:"AWS Feed"
    queryEntity: indicators
    results: null
    runFromLastJobTime: false
  required: false
  value: {}
- description: This input determines if processed indicators that have the whitelist_review
    tag are reviewed in a new incident. To create an incident, enter any value other
    than 'No'.
  key: OpenIncidentToReviewIndicatorsManually
  playbookInputQuery: null
  required: false
  value:
    simple: "No"
name: TIM - Process AWS indicators
outputs: []
quiet: true
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2d8511f2-b8bc-4842-8874-6ef271963509
      iscommand: false
      name: ""
      version: -1
    taskid: 2d8511f2-b8bc-4842-8874-6ef271963509
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 510,
          "y": -260
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e0d82c1e-b451-4874-8866-4896a6c4a0d5
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: e0d82c1e-b451-4874-8866-4896a6c4a0d5
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 510,
          "y": 960
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.AWSIndicatorTagName
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: inputs.AWSIndicatorTagName
          operator: isNotEqualString
          right:
            value:
              simple: whitelist_review
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "29"
      "yes":
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 34dc11d3-f348-44ef-8555-1011411f6be1
      iscommand: false
      name: Is there a AWSIndicatorTagName input?
      type: condition
      version: -1
    taskid: 34dc11d3-f348-44ef-8555-1011411f6be1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 220,
          "y": 100
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        simple: ${inputs.AWSIndicatorTagName}
      indicatorsValues:
        complex:
          accessor: value}
          filters:
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.sourceBrands
              operator: isEqualString
              right:
                value:
                  simple: AWS Feed
          root: ${playbookQuery
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Adds the tag provided in the input to the indicator.
      id: 7b2f6701-ee75-459b-81ad-19b3e68a7763
      iscommand: true
      name: Tag AWS indicators with tag from inputs
      script: Builtin|||appendIndicatorField
      type: regular
      version: -1
    taskid: 7b2f6701-ee75-459b-81ad-19b3e68a7763
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 220,
          "y": 770
        }
      }
  "24":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: value
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: playbookQuery.sourceBrands
                    operator: isEqualString
                    right:
                      value:
                        simple: AWS Feed
                root: playbookQuery
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 57d3f421-ebd7-43f3-82fc-12bdef480b6d
      iscommand: false
      name: Are there filtered results?
      type: condition
      version: -1
    taskid: 57d3f421-ebd7-43f3-82fc-12bdef480b6d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 510,
          "y": -80
        }
      }
  "25":
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        simple: whitelist_review
      indicatorsValues:
        complex:
          accessor: value}
          filters:
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.sourceBrands
              operator: isEqualString
              right:
                value:
                  simple: AWS Feed
          root: ${playbookQuery
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Adds the whitelist_review tag to the indicator.
      id: 776d5507-566e-4c62-89e2-b7ecc22cbee8
      iscommand: true
      name: Tag AWS indicators with tag whitelist review
      script: Builtin|||appendIndicatorField
      type: regular
      version: -1
    taskid: 776d5507-566e-4c62-89e2-b7ecc22cbee8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -230,
          "y": 440
        }
      }
  "26":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.OpenIncidentToReviewIndicatorsManually
          operator: isNotEqualString
          right:
            value:
              simple: "No"
      label: "yes"
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "27"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 97318052-4be2-4f70-8be3-98c89abed4d6
      iscommand: false
      name: Open manual review incident?
      type: condition
      version: -1
    taskid: 97318052-4be2-4f70-8be3-98c89abed4d6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -230,
          "y": 595
        }
      }
  "27":
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 2
    scriptarguments:
      name:
        simple: Review Indicators Manually For Whitelisting
      type:
        simple: Review Indicators Manually For Whitelisting
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Open new manual review incident
      id: a1be0d70-f176-412d-88d6-530847a6cc7c
      iscommand: true
      name: Create Process Indicators Manually incident
      script: Builtin|||createNewIncident
      type: regular
      version: -1
    taskid: a1be0d70-f176-412d-88d6-530847a6cc7c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -610,
          "y": 770
        }
      }
  "28":
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 60b07254-a36f-4a7c-89ec-006cd00cb7f8
      iscommand: false
      name: Auto Approve
      type: title
      version: -1
    taskid: 60b07254-a36f-4a7c-89ec-006cd00cb7f8
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 220,
          "y": 480
        }
      }
  "29":
    continueonerrortype: ""
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 67bff4f9-3905-418e-853d-523fb4c8d253
      iscommand: false
      name: Manually review
      type: title
      version: -1
    taskid: 67bff4f9-3905-418e-853d-523fb4c8d253
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -230,
          "y": 300
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1285,
        "width": 1500,
        "x": -610,
        "y": -260
      }
    }
  }
