contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: Phishing Investigation - Generic v2_DEMO Contribution Pack
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: |-
  Enrich IP addresses using one or more integrations.

  - Resolve IP addresses to hostnames (DNS)
  - Provide threat information
  - Separate internal and external addresses
id: 705c8576-ad2b-4398-822f-5d350f1b09c8
inputs:
- description: The IP address to enrich.
  key: IP
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Address
      root: IP
      transformers:
      - operator: uniq
- description: 'A CSV list of IP address ranges (in CIDR notation). Use this list
    to check if an IP address is found within a set of IP address ranges. For example:
    "172.16.0.0/12,10.0.0.0/8,192.168.0.0/16" (without quotes). If a list is not provided,
    will use default list provided in the IsIPInRanges script (the known IPv4 private
    address ranges).'
  key: InternalRange
  playbookInputQuery: null
  required: false
  value:
    simple: inputs.InternalRange
- description: Whether to convert the IP address to a hostname using a DNS query (True/False).
  key: ResolveIP
  playbookInputQuery: null
  required: true
  value:
    complex:
      root: inputs.ResolveIP
name: IP Enrichment - External
outputs:
- contextPath: IP
  description: The IP address objects.
  type: unknown
- contextPath: DBotScore
  description: Indicator, Score, Type, and Vendor.
  type: unknown
- contextPath: Endpoint
  description: The endpoint's object.
  type: unknown
- contextPath: Endpoint.Hostname
  description: The hostname to enrich.
  type: string
- contextPath: Endpoint.OS
  description: Endpoint operating system.
  type: string
- contextPath: Endpoint.IP
  description: A list of endpoint IP addresses.
- contextPath: Endpoint.MAC
  description: A list of endpoint MAC addresses.
- contextPath: Endpoint.Domain
  description: Endpoint domain name.
  type: string
sourceplaybookid: IP Enrichment - External - Generic v2
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c5befb77-73e5-4be5-880e-ec528a15aebe
      iscommand: false
      name: ""
      version: -1
    taskid: c5befb77-73e5-4be5-880e-ec528a15aebe
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 595ecdaa-c973-466f-8310-81433bc02255
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 595ecdaa-c973-466f-8310-81433bc02255
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1710
        }
      }
  "27":
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "40"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 661ce0c3-39f9-47bc-8035-249efa22609c
      iscommand: false
      name: Enrich external IP addresses
      type: title
      version: -1
    taskid: 661ce0c3-39f9-47bc-8035-249efa22609c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "28":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IP
          operator: isExists
          right:
            value: {}
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.IP
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "39"
      "yes":
      - "34"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determine whether the playbook's input contains at least one IP
        address.
      id: 7d72ee00-8ac1-49ba-86e1-5c2a448c50ae
      iscommand: false
      name: Are there any IP addresses?
      type: condition
      version: -1
    taskid: 7d72ee00-8ac1-49ba-86e1-5c2a448c50ae
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "34":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: inputs.ResolveIP
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    continueonerrortype: ""
    id: "34"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "27"
      "yes":
      - "35"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether the "ResolveIP" parameter is set to "True".
      id: 6f6a9864-46c6-45db-8c94-67f6ae6223f1
      iscommand: false
      name: Resolve the IP address?
      type: condition
      version: -1
    taskid: 6f6a9864-46c6-45db-8c94-67f6ae6223f1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "35":
    continueonerror: true
    continueonerrortype: ""
    id: "35"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    reputationcalc: 2
    scriptarguments:
      ip:
        complex:
          root: inputs.IP
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Convert the IP address to a hostname using DNS query.
      id: a7323660-21ee-43d2-8734-7282c67100d9
      iscommand: false
      name: IP to Hostname (DNS)
      script: IPToHost
      type: regular
      version: -1
    taskid: a7323660-21ee-43d2-8734-7282c67100d9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 895
        }
      }
  "39":
    continueonerrortype: ""
    id: "39"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bca0d4fc-fc99-4631-80f2-51f03d27463e
      iscommand: false
      name: No External IP Address
      type: title
      version: -1
    taskid: bca0d4fc-fc99-4631-80f2-51f03d27463e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 735
        }
      }
  "40":
    continueonerror: true
    continueonerrortype: ""
    id: "40"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "41"
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.IP
              operator: notIn
              right:
                iscontext: true
                value:
                  simple: inputs.InternalRange
          root: inputs.IP
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks the reputation of an IP address.
      id: de9d4911-149d-4189-8dc1-da2812207a20
      iscommand: true
      name: Query IP against threat intelligence sources
      script: '|||ip'
      type: regular
      version: -1
    taskid: de9d4911-149d-4189-8dc1-da2812207a20
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1215
        }
      }
  "41":
    continueonerrortype: ""
    id: "41"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "42"
    note: false
    quietmode: 0
    scriptarguments:
      indicatorsValues:
        complex:
          root: inputs.IP
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.enrich.indicators
      id: 7743c61e-9d7a-4276-81b8-f91ac4c572bd
      iscommand: true
      name: Enrich IPs
      script: Builtin|||enrichIndicators
      type: regular
      version: -1
    taskid: 7743c61e-9d7a-4276-81b8-f91ac4c572bd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1360
        }
      }
  "42":
    continueonerrortype: ""
    id: "42"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    scriptarguments:
      indicator:
        complex:
          root: inputs.IP
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Enrich indicators using Unit42
      id: b734bfa3-cf67-4d13-89a3-5592d0e7ae69
      iscommand: false
      name: Enrich with Unit42
      script: 40b261b7-ad22-48de-8634-a4f1ced06e73
      type: regular
      version: -1
    taskid: b734bfa3-cf67-4d13-89a3-5592d0e7ae69
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1530
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "28_39_#default#": 0.35,
      "34_27_#default#": 0.49,
      "34_35_yes": 0.53
    },
    "paper": {
      "dimensions": {
        "height": 1725,
        "width": 922.5,
        "x": 50,
        "y": 50
      }
    }
  }
