contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 414f4bec-2c5e-4ec2-8c11-1fe23aaa1cc1
inputs: []
name: tzManualTask
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0f86cf2b-0f45-4579-8015-ffb45101b55e
      iscommand: false
      name: ""
      version: -1
    taskid: 0f86cf2b-0f45-4579-8015-ffb45101b55e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    defaultassigneecomplex:
      simple: ikatz@paloaltonetworks.com
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2cd420f2-e3d4-4f83-84a8-00d9c0fe2ef9
      iscommand: false
      name: tmp
      type: regular
      version: -1
    taskid: 2cd420f2-e3d4-4f83-84a8-00d9c0fe2ef9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
