contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 4b4a66e2-b72a-478c-8a19-311cad19cdbf
inputs:
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: sourceBrands:"Covid19 Feed"
    queryEntity: indicators
    results: null
    runFromLastJobTime: true
  required: false
  value: {}
name: enrich indicators
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d9a6af3f-6360-4dde-850d-300a60d2a9f0
      iscommand: false
      name: ""
      version: -1
    taskid: d9a6af3f-6360-4dde-850d-300a60d2a9f0
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: playbookQuery.value
          operator: isEmpty
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0528aa69-85bb-40ca-8aa4-7fccd3ef439b
      iscommand: false
      name: check if exists
      type: condition
      version: -1
    taskid: 0528aa69-85bb-40ca-8aa4-7fccd3ef439b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d6467417-6a47-4190-8509-f37a54dd163a
      iscommand: false
      name: done
      type: title
      version: -1
    taskid: d6467417-6a47-4190-8509-f37a54dd163a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      indicatorsValues:
        simple: ${playbookQuery.value}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.enrich.indicators
      id: 507050bd-4e4e-4a41-8ccd-bfd74b4815cc
      iscommand: true
      name: enrich
      script: Builtin|||enrichIndicators
      type: regular
      version: -1
    taskid: 507050bd-4e4e-4a41-8ccd-bfd74b4815cc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 870,
          "y": 350
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b8fdb492-71d7-4fb7-87be-d628caccb013
      iscommand: false
      name: done
      type: title
      version: -1
    taskid: b8fdb492-71d7-4fb7-87be-d628caccb013
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 870,
          "y": 550
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 565,
        "width": 800,
        "x": 450,
        "y": 50
      }
    }
  }
