contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.5.0
    itemVersion: 1.12.8
    packID: CrowdStrikeFalcon
    packName: CrowdStrike Falcon
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook is part of the 'Malware Investigation And Response' pack.
  For more information, refer to https://xsoar.pan.dev/docs/reference/packs/malware-investigation-and-response.
  This playbook searches across the organization for other endpoints associated with
  a specific SHA256 hash.
id: CrowdStrike Falcon - Search Endpoints By Hash
inputs:
- description: The SHA256 file hash to search for.
  key: FileSha256
  playbookInputQuery: null
  required: false
  value: {}
- description: The ID of the host that originated the detection.
  key: HostId
  playbookInputQuery: null
  required: false
  value: {}
name: CrowdStrike Falcon - Search Endpoints By Hash
outputs:
- contextPath: Endpoint
  description: Additional hosts that have the SHA256 present.
  type: string
- contextPath: CrowdStrike.IOC.DeviceCount
  description: The number of devices the IOC ran on.
  type: number
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fdebf4c2-18fa-45ad-8931-a1df035a26d8
      iscommand: false
      name: ""
      version: -1
    taskid: fdebf4c2-18fa-45ad-8931-a1df035a26d8
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 170,
          "y": -90
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      type:
        simple: sha256
      value:
        simple: ${inputs.FileSha256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns a list of device IDs an indicator ran on.
      id: 9ce410b8-ddde-4690-8625-2cfab080cd83
      iscommand: true
      name: Search for hash in enviorment
      script: '|||cs-falcon-device-ran-on'
      type: regular
      version: -1
    taskid: 9ce410b8-ddde-4690-8625-2cfab080cd83
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 680,
          "y": 560
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      type:
        simple: sha256
      value:
        simple: ${inputs.FileSha256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: The number of hosts that observed the provided IOC.
      id: 04610f87-fee9-4de1-8980-1649f61b38d0
      iscommand: true
      name: Count hash in the environment
      script: '|||cs-falcon-device-count-ioc'
      type: regular
      version: -1
    taskid: 04610f87-fee9-4de1-8980-1649f61b38d0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0204bfc2-fc2d-483c-869b-8f85d0580b31
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 0204bfc2-fc2d-483c-869b-8f85d0580b31
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 170,
          "y": 930
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: CrowdStrike.IOC.DeviceCount
          operator: greaterThanOrEqual
          right:
            value:
              simple: "2"
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9b555544-59aa-45db-81b2-a12eb98fc56e
      iscommand: false
      name: Was the hash detected on additional hosts?
      type: condition
      version: -1
    taskid: 9b555544-59aa-45db-81b2-a12eb98fc56e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 380
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: CrowdStrike.DeviceID
              operator: notInList
              right:
                iscontext: true
                value:
                  simple: inputs.HostId
          root: CrowdStrike.DeviceID
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns information about an endpoint.
      id: f7a79437-c0fa-4613-84fa-22581196d8ef
      iscommand: true
      name: Enrich endpoint details for non original host
      script: '|||endpoint'
      type: regular
      version: -1
    taskid: f7a79437-c0fa-4613-84fa-22581196d8ef
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 680,
          "y": 760
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: CrowdstrikeFalcon
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if the integration brand is available. Otherwise
        returns 'no'.
      id: 13169d17-92b3-4cbf-8930-86e9b5d6f265
      iscommand: false
      name: Is Crowdstrike Falcon  enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 13169d17-92b3-4cbf-8930-86e9b5d6f265
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 170,
          "y": 40
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1085,
        "width": 890,
        "x": 170,
        "y": -90
      }
    }
  }
