contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.5.0
    itemVersion: 1.12.8
    packID: CrowdStrikeFalcon
    packName: CrowdStrike Falcon
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  This playbook is part of the 'Malware Investigation And Response' pack. For more information, refer to https://xsoar.pan.dev/docs/reference/packs/malware-investigation-and-response.
  This playbook verifies and sets the policy actions applied by CrowdStrike Falcon.
id: CrowdStrike Falcon Malware - Verify Containment Actions
inputs:
- description: The path that contains the detection results.
  key: PolicyBehaviourDetails
  playbookInputQuery: null
  required: false
  value: {}
name: CrowdStrike Falcon Malware - Verify Containment Actions
outputs:
- contextPath: Policy.State
  description: Is the policy active?
  type: string
- contextPath: Host.State
  description: Is the host isolated?
  type: string
- contextPath: Process.State
  description: Was the process contained?
  type: string
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e7c7d902-36bd-4b88-8ef6-c3e596be918a
      iscommand: false
      name: ""
      version: -1
    taskid: e7c7d902-36bd-4b88-8ef6-c3e596be918a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 200,
          "y": -380
        }
      }
  "1":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: Detection.Behavior.policy_disabled
          operator: isEqualString
          right:
            value:
              simple: "false"
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Is policy enabled?
      id: 15d703b6-7cd5-4a4e-856d-11141cec0875
      iscommand: false
      name: Is policy enabled?
      type: condition
      version: -1
    taskid: 15d703b6-7cd5-4a4e-856d-11141cec0875
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Policy.State
      value:
        simple: Not Active
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sets a value in context under the key you entered.
      id: 0aed7220-4345-4618-884a-e09854131ef8
      iscommand: false
      name: Set policy status not active
      script: Set
      type: regular
      version: -1
    taskid: 0aed7220-4345-4618-884a-e09854131ef8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 380
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Policy.State
      value:
        simple: Active
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 76f47710-f7d5-477e-8580-796e1083c4fd
      iscommand: false
      name: Set policy status active
      script: Set
      type: regular
      version: -1
    taskid: 76f47710-f7d5-477e-8580-796e1083c4fd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1170,
          "y": 380
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: be369256-7e95-4bf2-81b6-3cf05ceb26c8
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: be369256-7e95-4bf2-81b6-3cf05ceb26c8
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 200,
          "y": 1180
        }
      }
  "5":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: Detection.Behavior.quarantine_machine
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Was host isolated?
      id: 498d0b00-bd30-4bb8-8e24-ecf6d97e8e5d
      iscommand: false
      name: Was host isolated?
      type: condition
      version: -1
    taskid: 498d0b00-bd30-4bb8-8e24-ecf6d97e8e5d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 830,
          "y": 680
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Host.State
      value:
        simple: Isolated
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 2ddbc174-fc63-4b7c-8a86-282ca82d80c2
      iscommand: false
      name: Set host isolated
      script: Set
      type: regular
      version: -1
    taskid: 2ddbc174-fc63-4b7c-8a86-282ca82d80c2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1030,
          "y": 860
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Host.State
      value:
        simple: Not Isolated
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: efd68ab1-05fb-479b-8b00-dfd720f014b9
      iscommand: false
      name: Set host no isolated
      script: Set
      type: regular
      version: -1
    taskid: efd68ab1-05fb-479b-8b00-dfd720f014b9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 630,
          "y": 860
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d71558d5-a17b-4077-856b-e2c7819cb716
      iscommand: false
      name: Policy State
      type: title
      version: -1
    taskid: d71558d5-a17b-4077-856b-e2c7819cb716
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": -75
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7259fb74-92b6-4084-8f04-ee58d84a0671
      iscommand: false
      name: Host State
      type: title
      version: -1
    taskid: 7259fb74-92b6-4084-8f04-ee58d84a0671
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 830,
          "y": 555
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 15f02b8f-ff2c-46ca-8f8d-87958f36e139
      iscommand: false
      name: Done Host State
      type: title
      version: -1
    taskid: 15f02b8f-ff2c-46ca-8f8d-87958f36e139
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 840,
          "y": 1030
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 64484bbc-8000-46e9-8d21-4f8a06eb8d75
      iscommand: false
      name: Process State
      type: title
      version: -1
    taskid: 64484bbc-8000-46e9-8d21-4f8a06eb8d75
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1930,
          "y": 555
        }
      }
  "13":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: Detection.Behavior.kill_process
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: process killed
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: Detection.Behavior.suspend_process
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: process suspended
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: Detection.Behavior.process_blocked
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: Process blocked
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "17"
      Process blocked:
      - "18"
      process killed:
      - "15"
      process suspended:
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Was process handled?
      id: 748be87f-33af-415f-8b5a-3fe0bed1677e
      iscommand: false
      name: Was process handled?
      type: condition
      version: -1
    taskid: 748be87f-33af-415f-8b5a-3fe0bed1677e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1930,
          "y": 670
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Process.State
      value:
        simple: Suspended
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: a5b33061-f3d9-4eb1-8459-c00fc5978435
      iscommand: false
      name: Set process suspended
      script: Set
      type: regular
      version: -1
    taskid: a5b33061-f3d9-4eb1-8459-c00fc5978435
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1930,
          "y": 860
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Process.State
      value:
        simple: Killed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: dd702688-dfae-4463-8e0f-8d5e8ae552cc
      iscommand: false
      name: Set process killed
      script: Set
      type: regular
      version: -1
    taskid: dd702688-dfae-4463-8e0f-8d5e8ae552cc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1530,
          "y": 860
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b87386a4-4266-425b-868f-7da9bcedcf8c
      iscommand: false
      name: Done Host State
      type: title
      version: -1
    taskid: b87386a4-4266-425b-868f-7da9bcedcf8c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1740,
          "y": 1030
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Process.State
      value:
        simple: No Action Taken
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: f20c30ab-2b68-4522-830c-79b4c8f53253
      iscommand: false
      name: Set no action taken
      script: Set
      type: regular
      version: -1
    taskid: f20c30ab-2b68-4522-830c-79b4c8f53253
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 2730,
          "y": 860
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Process.State
      value:
        simple: Blocked
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 53a03f32-0e2a-44c4-8511-9569737270b2
      iscommand: false
      name: Set process blocked
      script: Set
      type: regular
      version: -1
    taskid: 53a03f32-0e2a-44c4-8511-9569737270b2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 2330,
          "y": 860
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Detection.Behavior
      value:
        complex:
          root: inputs.PolicyBehaviourDetails
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 282d6e1e-fc71-4571-8089-0ebc1404c838
      iscommand: false
      name: Get full detection details
      script: Set
      type: regular
      version: -1
    taskid: 282d6e1e-fc71-4571-8089-0ebc1404c838
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 45
        }
      }
  "20":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.PolicyBehaviourDetails
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Is there a policy object?
      id: e5ba8aa5-c0b8-4a58-85fe-7566ede7a5a3
      iscommand: false
      name: Is there a policy object?
      type: condition
      version: -1
    taskid: e5ba8aa5-c0b8-4a58-85fe-7566ede7a5a3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 200,
          "y": -250
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1625,
        "width": 2910,
        "x": 200,
        "y": -380
      }
    }
  }
